# Generated by Django 4.1.7 on 2023-03-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteCalculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('document', models.CharField(max_length=20)),
                ('code_zip', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('consumption', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tariff', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tariff_type', models.CharField(max_length=20)),
                ('tariff_type_consumption', models.CharField(choices=[('low', 'Low'), ('median', 'Median'), ('high', 'High')], default='', max_length=10)),
            ],
        ),
    ]
