# Generated by Django 4.1.7 on 2023-03-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator_app', '0005_alter_clientecalculator_applied_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientecalculator',
            name='applied_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='clientecalculator',
            name='coverage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
